@switch($month)
    @case('01')
        Januari
        @break
    @case('02')
        Februari
        @break
    @case('03')
        Maret
        @break
    @case('04')
        April
        @break
    @case('05')
        Mei
        @break
    @case('06')
        Juni
        @break
    @case('07')
        Juli
        @break
    @case('08')
        Agustus
        @break
    @case('09')
        September
        @break
    @case('10')
        Oktober
        @break
    @case('11')
        November
        @break
    @case('12')
        Desember
        @break;
@endswitch
